### ISSUE TITLE
Crash while running fresh install

### ISSUE THREAD

**Issue by patrickfrank1** [birnstiel/dsharp_opac#1]
Hello,

I just downloaded release 1.1.0 and installed it using pip accordingly. However when running /notebooks/opacity_package_test.ipynb I get the following error:

AttributeError: module 'dsharp_opac' has no attribute 'diel_luca'

It seems like this function is not implemented (yet). Is it important for using the package?

Best, Patrick

**Comment by birnstiel** [comment]
Hello,

Thanks for checking. This is not a big problem. This is a somewhat older notebook where I forgot to update some names after restructuring the package. So it was just a problem of the notebook, not the package. It should be fixed now.
